import { Category, Product, Review, BuyingGuide, Comparison, BlogPost, Author, Room, Aesthetic, Setup } from "@/types";

export const mockRooms: Room[] = [
  {
    id: "room-bedroom",
    name: "Bedroom",
    slug: "bedroom",
    description: "Serene, comfortable, and restful sanctuary designs focused on calm lighting and soothing textures.",
    image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&auto=format&fit=crop&q=80",
    seoTitle: "Aesthetic Bedroom Setups & Furniture Discoveries",
    seoDescription: "Create a soothing, aesthetic bedroom setup with curated furniture and lighting.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "room-home-office",
    name: "Home Office",
    slug: "home-office",
    description: "Inspiring workspace setups that balance ergonomic posture with minimalist, distraction-free aesthetic design.",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&auto=format&fit=crop&q=80",
    seoTitle: "Aesthetic Home Office & Desk Setups",
    seoDescription: "Explore minimal, Japandi, and warm neutral desk setups for your home office.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "room-living-room",
    name: "Living Room",
    slug: "living-room",
    description: "Inviting communal spaces featuring organic shapes, warm lighting, and cozy lounge setups.",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80",
    seoTitle: "Living Room Aesthetic Inspiration & Curated Finds",
    seoDescription: "Discover beautiful couches, coffee tables, and lighting for your living room.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "room-kitchen",
    name: "Kitchen",
    slug: "kitchen",
    description: "Functional yet visually striking kitchen accoutrements, specialty coffee bars, and countertop aesthetics.",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80",
    seoTitle: "Aesthetic Kitchen & Coffee Station Setups",
    seoDescription: "Elevate your kitchen and morning brew corner with curated appliances and ceramics.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "room-bathroom",
    name: "Bathroom",
    slug: "bathroom",
    description: "Spa-like rituals and clean vanity organization made with natural stone, wood, and warm lighting.",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80",
    seoTitle: "Spa & Aesthetic Bathroom Designs",
    seoDescription: "Transform your bathroom into a luxury sanctuary with aesthetic accents.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "room-dining",
    name: "Dining",
    slug: "dining",
    description: "Thoughtful dining spaces built for intimate meals and memorable visual gatherings.",
    image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&auto=format&fit=crop&q=80",
    seoTitle: "Aesthetic Dining Room Setups",
    seoDescription: "Curated dining tables, seating, and mood lighting.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "room-balcony",
    name: "Balcony",
    slug: "balcony",
    description: "Lush outdoor nooks and terrace setups designed for fresh air and cozy evening lounge sessions.",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&auto=format&fit=crop&q=80",
    seoTitle: "Aesthetic Balcony & Patio Setups",
    seoDescription: "Small outdoor balcony inspiration with warm string lights and outdoor furniture.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "room-entryway",
    name: "Entryway",
    slug: "entryway",
    description: "Welcoming entryway vignettes with ambient lamps, wooden catchalls, and sleek mirrors.",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    seoTitle: "Aesthetic Entryway & Foyer Concepts",
    seoDescription: "Create a memorable first impression with welcoming entryway decor.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockAesthetics: Aesthetic[] = [
  {
    id: "aes-minimalist",
    name: "Minimalist",
    slug: "minimalist",
    description: "Clean lines, functional beauty, and intentional negative space without visual clutter.",
    image: "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?w=800&auto=format&fit=crop&q=80",
    colorHex: "#e5e5e5",
    seoTitle: "Minimalist Home Decor & Setup Ideas",
    seoDescription: "Discover minimalist home products, clean desk setups, and clutter-free rooms.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "aes-cozy",
    name: "Cozy",
    slug: "cozy",
    description: "Soft tactile textiles, warm ambient glow, layered blankets, and comforting home touches.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80",
    colorHex: "#d4a373",
    seoTitle: "Cozy Home Aesthetic & Ambient Setups",
    seoDescription: "Warm textiles, ambient mood lighting, and cozy corner inspiration.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "aes-japandi",
    name: "Japandi",
    slug: "japandi",
    description: "The harmony of Scandinavian functionality and Japanese rustic minimalism (Wabi-Sabi).",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80",
    colorHex: "#ccd5ae",
    seoTitle: "Japandi Interior Style & Products",
    seoDescription: "Curated Japandi furniture, organic ceramics, and light wood aesthetics.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "aes-scandinavian",
    name: "Scandinavian",
    slug: "scandinavian",
    description: "Bright airy natural light, light wood tones, simple geometry, and cozy (Hygge) charm.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80",
    colorHex: "#fefae0",
    seoTitle: "Scandinavian Furniture & Home Decor",
    seoDescription: "Scandi room ideas, light oak furniture, and functional elegance.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "aes-boho",
    name: "Boho",
    slug: "boho",
    description: "Earthy rattan textures, trailing green plants, woven wall arts, and relaxed bohemian vibes.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80",
    colorHex: "#e9edc9",
    seoTitle: "Boho Chic Home Setups & Decor",
    seoDescription: "Bohemian home styling with rattan, indoor greenery, and warm woven goods.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "aes-modern",
    name: "Modern",
    slug: "modern",
    description: "Sleek architectural silhouettes, contrast accents, glass, matte metal, and polished finishes.",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&auto=format&fit=crop&q=80",
    colorHex: "#faedcd",
    seoTitle: "Modern Home Setup Inspiration",
    seoDescription: "Sleek modern furniture, architectural lamps, and contemporary spaces.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "aes-warm-neutral",
    name: "Warm Neutral",
    slug: "warm-neutral",
    description: "Soothing cream, beige, oat, and linen hues paired with raw natural timber tones.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop&q=80",
    colorHex: "#d6ccc2",
    seoTitle: "Warm Neutral Aesthetic Home Decor",
    seoDescription: "Earth-toned neutral rooms, cream textiles, and calming natural wood accent pieces.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "aes-dark-moody",
    name: "Dark & Moody",
    slug: "dark-moody",
    description: "Deep charcoal walls, warm amber glow, walnut furniture, and dramatic shadow accents.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&auto=format&fit=crop&q=80",
    colorHex: "#2b2d42",
    seoTitle: "Dark & Moody Interior Aesthetic",
    seoDescription: "Dramatic dark walnut, amber lamps, and cozy moody room setups.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "aes-luxury",
    name: "Luxury",
    slug: "luxury",
    description: "Refined marble surfaces, brushed brass detailing, velvet upholstery, and statement pieces.",
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&auto=format&fit=crop&q=80",
    colorHex: "#d4af37",
    seoTitle: "Luxury Home Decor & Statement Pieces",
    seoDescription: "High-end aesthetic home upgrades, marble, brass, and designer lighting.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "aes-vintage",
    name: "Vintage",
    slug: "vintage",
    description: "Mid-century classics, retro brass, weathered leather, and timeless heirloom craftsmanship.",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80",
    colorHex: "#9a7b56",
    seoTitle: "Vintage & Mid-Century Home Finds",
    seoDescription: "Mid-century modern classics, retro brass lamps, and vintage aesthetic home finds.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockCategories: Category[] = [
  {
    id: "cat-lighting",
    name: "Lighting & Lamps",
    slug: "lighting",
    description: "Warm ambient glow, sculptural desk lamps, and soothing floor lights.",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80",
    parentId: null,
    seoTitle: "Aesthetic Home Lighting & Desk Lamps",
    seoDescription: "Find ambient lamps, cordless nightstand lights, and warm glow fixtures.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-seating",
    name: "Seating & Chairs",
    slug: "seating",
    description: "Ergonomic desk chairs, cozy accent armchairs, and minimalist lounge seating.",
    image: "https://images.unsplash.com/photo-1580481072645-022f9a6d8310?w=800&auto=format&fit=crop&q=80",
    parentId: null,
    seoTitle: "Aesthetic Ergonomic Chairs & Lounge Seating",
    seoDescription: "Beautiful office chairs and accent armchairs for cozy spaces.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-desks-tables",
    name: "Desks & Tables",
    slug: "desks-tables",
    description: "Solid oak standing desks, Japandi coffee tables, and minimalist nightstands.",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80",
    parentId: null,
    seoTitle: "Aesthetic Wooden Desks & Coffee Tables",
    seoDescription: "Minimalist standing desks, solid walnut dining, and side tables.",
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockProducts: Product[] = [
  {
    id: "prod-pleated-desk-lamp",
    title: "Pebble Wireless Rechargeable Pleated Table Lamp",
    slug: "pebble-wireless-pleated-table-lamp",
    asin: "B0B8X9K1LM",
    brand: "NordicGlow",
    description: "A charming cordless lamp with a pleated linen shade and dimmable warm LED bulb. Perfect for nightstands, desk corners, or cozy coffee tables.",
    shortDescription: "Cordless dimmable lamp with pleated linen shade for warm ambient mood lighting.",
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80"
    ],
    affiliateUrl: "https://www.amazon.com/dp/B0B8X9K1LM/?tag=gearcurator-20",
    amazonUrl: "https://www.amazon.com/dp/B0B8X9K1LM",
    marketplace: "US",
    status: "PUBLISHED",
    source: "MANUAL",
    featured: true,
    badgeLabel: "Best for Minimalist Setups",
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),

    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80"
    ],
    buyUrl: "https://www.amazon.com/dp/B0B8X9K1LM/?tag=gearcurator-20",
    price: 49.99,
    currency: "USD",
    rating: 4.9,
    isFeatured: true,
    editorialScore: 9.7,
    pros: [
      "Completely wireless USB-C rechargeable battery lasts up to 18 hours",
      "Soft pleated shade creates a diffused, flicker-free evening glow",
      "Touch-controlled dimming with 3 color temperature settings",
      "Compact footprint fits seamlessly on small nightstands"
    ],
    cons: [
      "Requires charging every few days with heavy evening use",
      "Not designed for bright task reading work"
    ],
    aiSummary: "The Pebble Pleated Lamp brings Scandinavian Hygge vibes to any room corner. Its cordless design allows effortless placement without messy power cables cluttering your aesthetic setup.",
    categoryId: "cat-lighting",
    rooms: [mockRooms[0], mockRooms[1], mockRooms[2]],
    aesthetics: [mockAesthetics[0], mockAesthetics[2], mockAesthetics[3], mockAesthetics[6]],
    specifications: {
      "Power Source": "Rechargeable 4000mAh Battery",
      "Battery Life": "8 - 20 Hours",
      "Light Temperature": "2700K Warm White",
      "Control": "Touch Dimmer",
      "Height": "11.4 inches"
    },
  },
  {
    id: "prod-oak-standing-desk",
    title: "Ergonomic Solid White Oak Motorized Standing Desk",
    slug: "solid-white-oak-standing-desk",
    asin: "B09M2K918P",
    brand: "Kavala Studio",
    description: "Crafted from sustainable solid white oak with hand-rubbed organic oil finish and dual ultra-quiet electric motor legs.",
    shortDescription: "Solid oak motorized desk blending ergonomic health with natural Japandi timber aesthetics.",
    images: [
      "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80"
    ],
    affiliateUrl: "https://www.amazon.com/dp/B09M2K918P/?tag=gearcurator-20",
    amazonUrl: "https://www.amazon.com/dp/B09M2K918P",
    marketplace: "US",
    status: "PUBLISHED",
    source: "MANUAL",
    featured: true,
    badgeLabel: "Editor's Pick",
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),

    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80",
    gallery: [],
    buyUrl: "https://www.amazon.com/dp/B09M2K918P/?tag=gearcurator-20",
    price: 649.00,
    currency: "USD",
    rating: 4.8,
    isFeatured: true,
    editorialScore: 9.5,
    pros: [
      "Gorgeous real solid wood grain top with bevelled organic edges",
      "Dual motors lift up to 300 lbs smoothly and silently",
      "Programmable memory controller with OLED display",
      "Integrated under-desk cable management tray included"
    ],
    cons: [
      "Heavy package requires two people for assembly",
      "Premium solid wood price tier"
    ],
    aiSummary: "If you dislike industrial-looking metal standing desks, this solid oak desk is the ideal compromise. It offers full motorized height customization while retaining the warmth of authentic timber furniture.",
    categoryId: "cat-desks-tables",
    rooms: [mockRooms[1], mockRooms[0]],
    aesthetics: [mockAesthetics[0], mockAesthetics[2], mockAesthetics[3], mockAesthetics[6]],
    specifications: {
      "Desktop Material": "Solid American White Oak",
      "Frame Material": "Heavy-Duty Powder Coated Steel",
      "Height Adjustment": "25\" to 51\"",
      "Weight Capacity": "300 lbs",
      "Warranty": "7 Years"
    },
  },
  {
    id: "prod-boucle-accent-chair",
    title: "Minimalist Bouclé Curved Lounge Accent Chair",
    slug: "minimalist-boucle-curved-lounge-accent-chair",
    asin: "B09X8J2K67",
    brand: "Modus Home",
    description: "Enveloping curved silhouette upholstered in rich ivory tactile bouclé fabric. Supported by hidden matte black brass legs.",
    shortDescription: "Sculptural curved lounge chair in cozy textured ivory bouclé.",
    images: [
      "https://images.unsplash.com/photo-1580481072645-022f9a6d8310?w=800&auto=format&fit=crop&q=80"
    ],
    affiliateUrl: "https://www.amazon.com/dp/B09X8J2K67/?tag=gearcurator-20",
    amazonUrl: "https://www.amazon.com/dp/B09X8J2K67",
    marketplace: "US",
    status: "PUBLISHED",
    source: "MANUAL",
    featured: true,
    badgeLabel: "Cozy Pick",
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),

    image: "https://images.unsplash.com/photo-1580481072645-022f9a6d8310?w=800&auto=format&fit=crop&q=80",
    gallery: [],
    buyUrl: "https://www.amazon.com/dp/B09X8J2K67/?tag=gearcurator-20",
    price: 329.00,
    currency: "USD",
    rating: 4.7,
    isFeatured: true,
    editorialScore: 9.3,
    pros: [
      "Stunning organic rounded aesthetic looks like high-end designer furniture",
      "Plush high-density foam cushioning with deep supportive seat",
      "Soft, stain-resistant nubby bouclé fabric texture"
    ],
    cons: [
      "Ivory color requires careful spot cleaning near pets or kids",
      "Fixed back height does not support full head rest"
    ],
    aiSummary: "A showstopping accent piece that instantly softens sharp modern rooms. Ideal for creating a cozy reading nook in your bedroom or living space.",
    categoryId: "cat-seating",
    rooms: [mockRooms[0], mockRooms[2], mockRooms[1]],
    aesthetics: [mockAesthetics[1], mockAesthetics[2], mockAesthetics[6], mockAesthetics[8]],
    specifications: {
      "Upholstery": "Premium Textured Bouclé Fabric",
      "Frame": "FSC-Certified Kiln-Dried Hardwood",
      "Weight Capacity": "280 lbs",
      "Seat Height": "17.5 inches"
    },
  },
  {
    id: "prod-fellow-stagg-kettle",
    title: "Fellow Stagg EKG Electric Gooseneck Pour-Over Kettle",
    slug: "fellow-stagg-ekg-electric-gooseneck-kettle",
    asin: "B077JBQZPX",
    brand: "Fellow",
    description: "The gold standard of aesthetic kettle design. Precise pour-over spout, variable temperature control, and sleek matte finish.",
    shortDescription: "Iconic matte black electric pour-over kettle with precise temperature dial.",
    images: [
      "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80"
    ],
    affiliateUrl: "https://www.amazon.com/dp/B077JBQZPX/?tag=gearcurator-20",
    amazonUrl: "https://www.amazon.com/dp/B077JBQZPX",
    marketplace: "US",
    status: "PUBLISHED",
    source: "MANUAL",
    featured: true,
    badgeLabel: "Great for Small Spaces",
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),

    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
    gallery: [],
    buyUrl: "https://www.amazon.com/dp/B077JBQZPX/?tag=gearcurator-20",
    price: 165.00,
    currency: "USD",
    rating: 4.8,
    isFeatured: true,
    editorialScore: 9.6,
    pros: [
      "Counterbalanced handle provides supreme pouring control",
      "LCD screen displays real-time and target temperature",
      "60-minute temperature hold mode",
      "Stunning minimalist countertop presence"
    ],
    cons: [
      "0.9 Liter capacity is smaller than standard electric kettles",
      "High price point for a single-purpose kettle"
    ],
    aiSummary: "Loved by interior stylists and specialty coffee baristas alike, the Fellow Stagg EKG elevates your morning brew into a mindful visual ritual.",
    categoryId: "cat-lighting",
    rooms: [mockRooms[3], mockRooms[1]],
    aesthetics: [mockAesthetics[0], mockAesthetics[2], mockAesthetics[5], mockAesthetics[7]],
    specifications: {
      "Capacity": "0.9 Liters",
      "Temperature Range": "135°F - 212°F",
      "Wattage": "1200W",
      "Body": "304 Stainless Steel"
    },
  }
];

export const mockSetups: Setup[] = [
  {
    id: "setup-minimal-home-office",
    title: "Minimal Warm Oak Home Office",
    slug: "minimal-home-office",
    description: "A calming work-from-home corner combining natural oak textures, ambient pleated lighting, and clean cable-free ergonomics.",
    heroImage: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&auto=format&fit=crop&q=80",
    published: true,
    featured: true,
    roomId: "room-home-office",
    room: mockRooms[1],
    aesthetics: [mockAesthetics[0], mockAesthetics[2], mockAesthetics[6]],
    products: [mockProducts[0], mockProducts[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "setup-japandi-bedroom-nook",
    title: "Japandi Sanctuary Bedroom Setup",
    slug: "japandi-sanctuary-bedroom",
    description: "Soothing natural linen bedding, warm cordless pleated lamps, and soft curved bouclé seating built for quiet morning light.",
    heroImage: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&auto=format&fit=crop&q=80",
    published: true,
    featured: true,
    roomId: "room-bedroom",
    room: mockRooms[0],
    aesthetics: [mockAesthetics[2], mockAesthetics[1], mockAesthetics[6]],
    products: [mockProducts[0], mockProducts[2]],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "setup-cozy-living-lounge",
    title: "Cozy Warm Neutral Living Room Lounge",
    slug: "cozy-warm-neutral-living-room",
    description: "Layered organic textures, rounded bouclé lounge chairs, and ambient mood lighting for cozy evening gatherings.",
    heroImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&auto=format&fit=crop&q=80",
    published: true,
    featured: true,
    roomId: "room-living-room",
    room: mockRooms[2],
    aesthetics: [mockAesthetics[1], mockAesthetics[6], mockAesthetics[3]],
    products: [mockProducts[2], mockProducts[0]],
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export const mockAuthors: Author[] = [
  {
    id: "auth-alex",
    name: "Alex Mercer",
    slug: "alex-mercer",
    bio: "Interior Stylist and Home Space Analyst.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "auth-evelyn",
    name: "Dr. Evelyn Vance",
    slug: "evelyn-vance",
    bio: "Spatial Designer and Lighting Specialist.",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export const mockReviews: Review[] = [
  {
    id: "rev-pebble-lamp",
    slug: "pebble-wireless-pleated-lamp-review",
    title: "Pebble Pleated Cordless Lamp Review: The Ultimate Mood Lighting?",
    excerpt: "We spent 3 months styling this cordless pleated table lamp in bedrooms and workspaces. Here is our verdict on battery life, dimming, and aesthetic impact.",
    content: `## Ambient Perfection Without the Cord

Finding the right table lamp often means dealing with unsightly power cords dangling off nightstands or desk edges. The **Pebble Cordless Pleated Lamp** solves this with an elegant rechargeable battery design.

### Design & Craftsmanship
The lamp features a warm pleated shade that softens LED harshness into a gentle golden glow. The matte ceramic-look base feels weighted and steady.

### Real World Use
Whether placed on a cozy dining table during dinner or brought to a balcony nook for late-night reading, the 18-hour battery life provides immense placement freedom.`,
    rating: 4.9,
    verdict: "An affordable, versatile mood lighting upgrade for cozy and Japandi interiors.",
    author: mockAuthors[0],
    authorId: mockAuthors[0].id,
    isPublished: true,
    isAiGenerated: false,
    productId: "prod-pleated-desk-lamp",
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export const mockBuyingGuides: BuyingGuide[] = [
  {
    id: "guide-cozy-bedroom",
    slug: "15-amazon-finds-to-create-a-japandi-bedroom",
    title: "15 Amazon Finds to Create a Serene Japandi Bedroom Setup",
    excerpt: "Transform your bedroom into a soothing sanctuary with warm woods, pleated cordless lighting, and textured bouclé textiles.",
    content: `## Designing a Peaceful Japandi Sanctuary

Japandi style blends Japanese Wabi-Sabi simplicity with Scandinavian warmth. By paring back clutter and focusing on tactile natural materials, your bedroom becomes a calm shelter from daily busyness.

### Key Elements of a Japandi Bedroom:
1. **Low-Profile Wooden Furniture:** Focus on clean timber grain like solid oak or natural ash.
2. **Warm Diffused Lighting:** Avoid harsh overhead ceiling lights. Use cordless lamps with linen shades.
3. **Organic Textiles:** Choose textured bouclé armchairs and washed linen bedding in oat or cream tones.`,
    featuredImage: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&auto=format&fit=crop&q=80",
    author: mockAuthors[0],
    authorId: mockAuthors[0].id,
    categoryId: "cat-lighting",
    roomId: "room-bedroom",
    seoTitle: "15 Japandi Bedroom Decor Finds on Amazon",
    seoDescription: "Curated Japandi bedroom products, low wood furniture, and ambient lighting.",
    products: [
      {
        buyingGuideId: "guide-cozy-bedroom",
        productId: "prod-pleated-desk-lamp",
        product: mockProducts[0],
        rank: 1,
        commentary: "Essential cordless nightstand illumination. Softens the room with delicate pleated shadows.",
      },
      {
        buyingGuideId: "guide-cozy-bedroom",
        productId: "prod-boucle-accent-chair",
        product: mockProducts[2],
        rank: 2,
        commentary: "Adds rich texture and organic rounded curves to quiet corner spaces.",
      }
    ],
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export const mockComparisons: Comparison[] = [];
export const mockBlogPosts: BlogPost[] = [];

